# Generated by Django 3.1 on 2020-08-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('schedule', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('bstartTime', models.TimeField()),
                ('bendTime', models.TimeField()),
            ],
        ),
    ]
