# Generated by Django 3.1 on 2020-08-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='schedule',
        ),
    ]
