# Generated by Django 3.1 on 2020-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_exam_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='schedule',
            field=models.DateField(blank=True, default=None),
        ),
    ]
