# Generated by Django 3.1 on 2020-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_exam_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invigilator',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='reservedfor',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='roomID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='venueID',
            field=models.IntegerField(default=None),
        ),
    ]
