# Generated by Django 3.1 on 2020-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200813_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='invigilator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='reservedfor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='venueID',
            field=models.IntegerField(),
        ),
    ]
