# Generated by Django 3.1 on 2020-08-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200813_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='schedule',
        ),
        migrations.AddField(
            model_name='exam',
            name='schedule',
            field=models.ManyToManyField(default=None, to='schedule.Schedule'),
        ),
    ]
