# Generated by Django 3.1 on 2020-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20200815_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assessor',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='certificateSchedule',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='exam',
            name='code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='componyId',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='exam',
            name='courseCode',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='medium',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='mode',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='recordId',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='exam',
            name='registrationSchedule',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='exam',
            name='resultSchedule',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='exam',
            name='sessionId',
            field=models.IntegerField(default=None),
        ),
    ]
