# Generated by Django 3.1 on 2020-08-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20200815_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='assessor',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='certificateSchedule',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='code',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='componyId',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='courseCode',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='recordId',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='registrationSchedule',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='resultSchedule',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='sessionId',
        ),
    ]
