# Generated by Django 3.1 on 2020-08-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='certificateSchedule',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='schedule',
            field=models.ManyToManyField(to='schedule.Schedule'),
        ),
    ]
