# Generated by Django 3.1 on 2020-08-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20200820_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='schedule',
        ),
    ]
