# Generated by Django 3.1 on 2020-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alert_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
