# Generated by Django 3.1 on 2020-08-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20200825_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room'),
        ),
    ]
