# Generated by Django 3.1 on 2020-08-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_assignment_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='dates',
        ),
    ]
