# Generated by Django 3.1 on 2020-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_remove_assignment_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weakdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='examDates',
            field=models.ManyToManyField(default=None, to='schedule.Weakdays'),
        ),
    ]
