# Generated by Django 3.1 on 2020-08-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20200827_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='registrationSchedule',
        ),
        migrations.AddField(
            model_name='exam',
            name='registrationSchedule',
            field=models.ManyToManyField(default=None, to='schedule.Registration'),
        ),
    ]
