# Generated by Django 3.1 on 2020-08-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_auto_20200827_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='exam',
        ),
        migrations.AddField(
            model_name='assignment',
            name='exam',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.exam'),
        ),
    ]
