# Generated by Django 3.1 on 2020-08-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_auto_20200828_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.exam'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.room'),
        ),
    ]
