# Generated by Django 3.1 on 2020-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_auto_20200903_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='SESSIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STARTTIME', models.CharField(max_length=8)),
                ('ENDTIME', models.CharField(max_length=8)),
                ('SESSIONCODE', models.CharField(max_length=5)),
            ],
        ),
    ]
