# Generated by Django 3.1 on 2020-09-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='recordId',
        ),
    ]
