# Generated by Django 3.1 on 2020-09-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_remove_exam_recordid'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=100)),
                ('examMode', models.CharField(max_length=100)),
                ('examMedium', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('room', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('regSchedule', models.IntegerField(default=None)),
                ('cerSchedule', models.IntegerField(default=None)),
                ('resSchedule', models.IntegerField(default=None)),
                ('examSchedule', models.ManyToManyField(default=None, to='schedule.Weakdays')),
            ],
        ),
    ]
