# Generated by Django 3.1 on 2020-09-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_masterschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterschedule',
            name='componyId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
