# Generated by Django 3.1 on 2020-09-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_masterschedule_componyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterschedule',
            name='examSchedule',
            field=models.ManyToManyField(blank=True, to='schedule.Weakdays'),
        ),
    ]
