# Generated by Django 3.1 on 2020-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_examsch_seatalloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatalloc',
            name='EXAMDATE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seatalloc',
            name='FILLED',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seatalloc',
            name='REGDATE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seatalloc',
            name='SEATS',
            field=models.IntegerField(default=0),
        ),
    ]
