# Generated by Django 3.1 on 2020-09-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0032_auto_20200916_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='examSch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.examsch'),
        ),
        migrations.AddField(
            model_name='events',
            name='seatAlloc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.seatalloc'),
        ),
    ]
