# Generated by Django 3.1 on 2020-09-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0033_auto_20200916_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterschedule',
            name='subcode',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
