# Generated by Django 3.1 on 2020-09-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0034_auto_20200917_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterschedule',
            name='cerSchedule',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='masterschedule',
            name='resSchedule',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
